antora:
  extensions:
    - '@antora/collector-extension'
    - '/Users/rwinch/code/spring-io/antora-extensions/main/lib/root-attachments-extension.js'
git:
  ensure_git_suffix: false
content:
  sources:
  - url: .
    branches: HEAD
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
  extensions:
    - '/Users/rwinch/code/spring-io/asciidoctor-extensions/main/lib/javadoc-extension.js'
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
runtime:
  log:
    failure_level: warn
    level: all
