site:
  title: Project
  start_page: java-project:ROOT:index.adoc
content:
  sources:
    - url: ./
      branches: [HEAD, main]
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true

pipeline:
  extensions:
    - require: ./antora/extensions/root-component-name.js