antora:
  extensions:
    - require: '@antora/collector-extension'
site:
  title: Spring Framework
  url: https://docs.spring.io/spring-framework/reference
  robots: allow
git:
  ensure_git_suffix: false
content:
  sources:
    - url: ./
      # Refname matching:
      # https://docs.antora.org/antora/latest/playbook/content-refname-matching/
      branches: ['1.0.x']
      tags: ['v1.0.23']
runtime:
  log:
    failure_level: warn
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
