git:
  ensure_git_suffix: false
content:
  sources:
  - url: .
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
    kroki-fetch-diagram: true
urls:
  latest_version_segment_strategy: redirect:to
  latest_version_segment: ''
  redirect_facility: httpd
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
