git:
  ensure_git_suffix: false
content:
  sources:
  - url: .
    branches: HEAD
asciidoc:
  extensions:
    - '@springio/asciidoctor-extensions/code-import-extension'
    - '@springio/asciidoctor-extensions/code-chomping-extension'
    - '@springio/asciidoctor-extensions/code-folding-extension'
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
    import-java: 'example$docs-src/main/java'
    chomp: default
urls:
  latest_version_segment: ''
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
