git:
  ensure_git_suffix: false
content:
  sources:
  - url: .
    branches: HEAD
asciidoc:
  attributes:
    page-pagination: ''
    hide-uri-scheme: '@'
urls:
  latest_version_segment: ''
ui:
  bundle:
    url: https://github.com/spring-io/antora-ui-spring/releases/download/latest/ui-bundle.zip
    snapshot: true
